plugins {
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '6.0.47'
}

version = '1.4.0'
group = 'net.pdy.goldenticket'
archivesBaseName = 'golden_ticket'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    copyIdeResources = true

    runs {
        client {
            def mcreatorJvmOptions = System.getenv('MCREATOR_JVM_OPTIONS')
            if (mcreatorJvmOptions) {
                jvmArgs += mcreatorJvmOptions.split("\\s+").findAll { it.trim() }.toList()
            }
            property("mixin.env.remapRefMap", "true")
            property("mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg")
        }

        server {
        }

        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                goldenticketmod {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/mirror" }
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
    maven { url = "https://cursemaven.com"}
    // create-delicious-teas一直拉取失败，暂时用本地库
    flatDir {
        dirs 'libs'
    }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'

    // 机械动力 (Create)
    implementation fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
    implementation(fg.deobf("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"))
    compileOnly(fg.deobf("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}"))
    runtimeOnly(fg.deobf("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}"))
    implementation(fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}"))
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")

    // Farmer's Delight
    implementation(fg.deobf("curse.maven:farmers-delight-398521:7801523"))
    // Create Confectionery
    implementation(fg.deobf("curse.maven:create-confectionery-531834:4835793"))
    // Create Tea
    // compileOnly fg.deobf("curse.maven:create-delicious-teas-1328556:6893693")
    implementation(fg.deobf("libs:createteas:1.0"))
    // Garnished
    implementation(fg.deobf("curse.maven:garnished-923277:7557977"))
    // Create Food
    implementation(fg.deobf("curse.maven:create-food-959439:7352721"))
    // JEI
    implementation(fg.deobf("curse.maven:jei-238222:7391695"))
    // apple skin
    implementation(fg.deobf("curse.maven:appleskin-248787:4770828"))
}

apply from: 'mcreator.gradle'

