buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.47'
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'

group = 'org.ccz3141'
version = mod_version
archivesBaseName = 'gt_moreplayers'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                gt_moreplayers { source sourceSets.main }
                // 重要：开发时同时加载核心模组
                goldenticketmod { source project(':golden_ticket').sourceSets.main }
            }
        }
        server {
            mods {
                gt_moreplayers { source sourceSets.main }
                goldenticketmod { source project(':golden_ticket').sourceSets.main }
            }
        }
        data {
            workingDirectory project.file('run-data')
            args '--mod', 'gt_moreplayers', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            mods {
                gt_moreplayers { source sourceSets.main }
                goldenticketmod { source project(':golden_ticket').sourceSets.main }
            }
        }
    }
}

mixin {
    add sourceSets.main, "gtmpmod.refmap.json"
    config "gtmpmod.mixins.json"
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    implementation fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation(fg.deobf("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"))
    compileOnly(fg.deobf("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}"))
    runtimeOnly(fg.deobf("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}"))
    implementation(fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}"))
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")

    implementation(fg.deobf("curse.maven:farmers-delight-398521:7801523"))
    implementation(fg.deobf("curse.maven:create-confectionery-531834:4835793"))
    implementation(fg.deobf("libs:createteas:1.0"))
    implementation(fg.deobf("curse.maven:garnished-923277:7557977"))
    implementation(fg.deobf("curse.maven:create-food-959439:7352721"))
    implementation(fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}"))
    implementation(fg.deobf("curse.maven:appleskin-248787:4770828"))
}

tasks.named('processResources', ProcessResources).configure {
}